// <auto-generated />
using System;
using Animu.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Animu.Data.Migrations
{
    [DbContext(typeof(AnimuDbContext))]
    [Migration("20220617165136_SeedTest")]
    partial class SeedTest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Animu.Data.Entities.Anime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Animes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0891b02f-6ed9-43b9-9f73-2848be072b20"),
                            ImageUrl = "https://cdn.myanimelist.net/images/anime/8/77831l.jpg",
                            Synopsis = "After dying a laughable and pathetic death on his way back from buying a game, high school student and recluse Kazuma Satou finds himself sitting before a beautiful but obnoxious goddess named Aqua. She provides the NEET with two options: continue on to heaven or reincarnate in every gamer's dream—a real fantasy world! Choosing to start a new life, Kazuma is quickly tasked with defeating a Demon King who is terrorizing villages. But before he goes, he can choose one item of any kind to aid him in his quest, and the future hero selects Aqua. But Kazuma has made a grave mistake—Aqua is completely useless! Unfortunately, their troubles don't end here; it turns out that living in such a world is far different from how it plays out in a game. Instead of going on a thrilling adventure, the duo must first work to pay for their living expenses. Indeed, their misfortunes have only just begun!",
                            Title = "Kono Subarashii Sekai ni Shukufuku wo!"
                        },
                        new
                        {
                            Id = new Guid("abab9632-5b43-4fb9-8377-43b698686445"),
                            ImageUrl = "https://cdn.myanimelist.net/images/anime/7/88019l.jpg",
                            Synopsis = "The final hour of the popular virtual reality game Yggdrasil has come. However, Momonga, a powerful wizard and master of the dark guild Ainz Ooal Gown, decides to spend his last few moments in the game as the servers begin to shut down. To his surprise, despite the clock having struck midnight, Momonga is still fully conscious as his character and, moreover, the non-player characters appear to have developed personalities of their own! Confronted with this abnormal situation, Momonga commands his loyal servants to help him investigate and take control of this new world, with the hopes of figuring out what has caused this development and if there may be others in the same predicament.",
                            Title = "Overlord"
                        },
                        new
                        {
                            Id = new Guid("dac27489-f999-48ec-a8de-661d192b08eb"),
                            ImageUrl = "https://cdn.myanimelist.net/images/anime/1071/106675l.jpg",
                            Synopsis = "The Fifth Holy Grail War in Fuyuki City has reached a turning point in which the lives of all participants are threatened as the hidden enemy finally reveals itself. As Shirou Emiya, Rin Toosaka, and Illyasviel von Einzbern discover the true, corruptive nature of the shadow that has been rampaging throughout the city, they realize just how dire the situation is. In order to protect their beloved ones, the group must hold their own against the seemingly insurmountable enemy force—even if some of those foes were once their allies, or perhaps, something more intimate. As the final act of this chaotic war commences, the ideals Shirou believes will soon be challenged by an excruciating dilemma: is it really possible to save a world where everything seems to have gone wrong?",
                            Title = "Fate/stay night: Heaven's Feel - III. Spring Song"
                        },
                        new
                        {
                            Id = new Guid("6503eae0-a8c8-4a30-9b71-9d1f689aa5ce"),
                            ImageUrl = "https://cdn.myanimelist.net/images/anime/7/72533l.jpg",
                            Synopsis = "The seemingly unimpressive Saitama has a rather unique hobby: being a hero. In order to pursue his childhood dream, Saitama relentlessly trained for three years, losing all of his hair in the process. Now, Saitama is so powerful, he can defeat any enemy with just one punch. However, having no one capable of matching his strength has led Saitama to an unexpected problem—he is no longer able to enjoy the thrill of battling and has become quite bored.  One day, Saitama catches the attention of 19-year-old cyborg Genos, who witnesses his power and wishes to become Saitama’s disciple. Genos proposes that the two join the Hero Association in order to become certified heroes that will be recognized for their positive contributions to society. Saitama, who is shocked that no one knows who he is, quickly agrees. Meeting new allies and taking on new foes, Saitama embarks on a new journey as a member of the Hero Association to experience the excitement of battle he once felt.",
                            Title = "One Punch Man"
                        },
                        new
                        {
                            Id = new Guid("9c571d74-b29c-4541-b396-e5d0770b9a46"),
                            ImageUrl = "https://cdn.myanimelist.net/images/anime/1065/117105l.jpg",
                            Synopsis = "The Fifth Holy Grail War continues, and the ensuing chaos results in higher stakes for all participants. Shirou Emiya continues to participate in the war, aspiring to be a hero of justice who saves everyone. He sets out in search of the truth behind a mysterious dark shadow and its murder spree, determined to defeat it. Meanwhile, Shinji Matou sets his own plans into motion, threatening Shirou through his sister Sakura Matou. Shirou and Rin Toosaka battle Shinji, hoping to relieve Sakura from the abuses of her brother. But the ugly truth of the Matou siblings begins to surface, and many dark secrets are exposed. Fate/stay night Movie: Heaven's Feel - II. Lost Butterfly continues to focus on the remaining Masters and Servants as they fight each other in the hopes of obtaining the Holy Grail. However, as darkness arises within Fuyuki City, even the state of their sacred war could be in danger.",
                            Title = "Fate/stay night: Heaven's Feel - II. Lost Butterfly"
                        },
                        new
                        {
                            Id = new Guid("c08bdbf7-cd84-4351-be0d-f738c4e6955b"),
                            ImageUrl = "https://cdn.myanimelist.net/images/anime/5/79183l.jpg",
                            Synopsis = "Eighth-grader Shigeo \"Mob\" Kageyama has tapped into his inner wellspring of psychic prowess at a young age. But the power quickly proves to be a liability when he realizes the potential danger in his skills. Choosing to suppress his power, Mob's only present use for his ability is to impress his longtime crush, Tsubomi, who soon grows bored of the same tricks. In order to effectuate control on his skills, Mob enlists himself under the wing of Arataka Reigen, a con artist claiming to be a psychic, who exploits Mob's powers for pocket change. Now, exorcising evil spirits on command has become a part of Mob's daily, monotonous life. However, the psychic energy he exerts is barely the tip of the iceberg; if his vast potential and unrestrained emotions run berserk, a cataclysmic event that would render him completely unrecognizable will be triggered. The progression toward Mob's explosion is rising and attempting to stop it is futile.",
                            Title = "Mob Psycho 100"
                        },
                        new
                        {
                            Id = new Guid("4b3d577b-f39f-4d25-80a8-fc9015ca273e"),
                            ImageUrl = "https://cdn.myanimelist.net/images/anime/1441/122795l.jpg",
                            Synopsis = "Corrupt politicians, frenzied nationalists, and other warmongering forces constantly jeopardize the thin veneer of peace between neighboring countries Ostania and Westalis. In spite of their plots, renowned spy and master of disguise \"Twilight\" fulfills dangerous missions one after another in the hope that no child will have to experience the horrors of war. In the bustling Ostanian city of Berlint, Twilight dons the alias of \"Loid Forger,\" an esteemed psychiatrist. However, his true intention is to gather intelligence on prominent politician Donovan Desmond, who only appears rarely in public at his sons' school: the prestigious Eden Academy. Enlisting the help of unmarried city hall clerk Yor Briar to act as his wife and adopting the curious six-year-old orphan Anya as his daughter, Loid enacts his master plan. He will enroll Anya in Eden Academy, where Loid hopes she will excel and give him the opportunity to meet Donovan without arousing suspicion. Unfortunately for Loid, even a man of his talents has trouble playing the figure of a loving father and husband. And just like Loid is hiding his true identity, Yor—who is an underground assassin known as \"Thorn Princess\"—and Anya—an esper who can read people's minds—have no plans to disclose their own secrets either. Although this picture-perfect family is founded on deception, the Forgers gradually come to understand that the love they share for one another trumps all else.",
                            Title = "Spy x Family"
                        },
                        new
                        {
                            Id = new Guid("f50a5dbd-8fcf-4977-90d9-fd416b1ffff5"),
                            ImageUrl = "https://cdn.myanimelist.net/images/anime/1883/117106l.jpg",
                            Synopsis = "The Holy Grail War: a violent battle between mages in which seven masters and their summoned servants fight for the Holy Grail, a magical artifact that can grant the victor any wish. Nearly 10 years ago, the final battle of the Fourth Holy Grail War wreaked havoc on Fuyuki City and took over 500 lives, leaving the city devastated. Shirou Emiya, a survivor of this tragedy, aspires to become a hero of justice like his rescuer and adoptive father, Kiritsugu Emiya. Despite only being a student, Shirou is thrown into the Fifth Holy Grail War when he accidentally sees a battle between servants at school and summons his own servant, Saber. When a mysterious shadow begins a murderous spree in Fuyuki City, Shirou aligns himself with Rin Toosaka, a fellow participant in the Holy Grail War, in order to stop the deaths of countless people. However, Shirou's feelings for his close friend Sakura Matou lead him deeper into the dark secrets surrounding the war and the feuding families involved.",
                            Title = "Fate/stay night: Heaven's Feel - I. Presage Flower"
                        });
                });

            modelBuilder.Entity("Animu.Data.Entities.Episode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnimeId");

                    b.ToTable("Episodes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3993668c-b04f-49bb-b837-02c89909cfe4"),
                            AnimeId = new Guid("c08bdbf7-cd84-4351-be0d-f738c4e6955b"),
                            Number = 8,
                            Title = "The Older Brother Bows: Destructive Intent",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/Zo7KpQEPMTri"
                        },
                        new
                        {
                            Id = new Guid("699d9a1a-247e-4008-9bcc-0571dcef2862"),
                            AnimeId = new Guid("abab9632-5b43-4fb9-8377-43b698686445"),
                            Number = 2,
                            Title = "Floor Guardians",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/vPQM1RP3AN0D"
                        },
                        new
                        {
                            Id = new Guid("b89d0ea5-1d1a-40e7-817a-07b38e5b609a"),
                            AnimeId = new Guid("c08bdbf7-cd84-4351-be0d-f738c4e6955b"),
                            Number = 10,
                            Title = "The Heinous Aura: Mastermind",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/EwgQL0ZTdRyP"
                        },
                        new
                        {
                            Id = new Guid("60c25d57-3552-4a0f-93fc-0a47e368d4a4"),
                            AnimeId = new Guid("6503eae0-a8c8-4a30-9b71-9d1f689aa5ce"),
                            Number = 12,
                            Title = "The Strongest Hero",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/imChvKvSHNP7"
                        },
                        new
                        {
                            Id = new Guid("13c2721d-83ff-436c-a1fb-0b8edc270df7"),
                            AnimeId = new Guid("c08bdbf7-cd84-4351-be0d-f738c4e6955b"),
                            Number = 5,
                            Title = "Ochimusa: Psychic Powers and Me",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/Pkur7ZX2Aq4z"
                        },
                        new
                        {
                            Id = new Guid("a376844d-e59d-4998-a915-114cedf2c972"),
                            AnimeId = new Guid("abab9632-5b43-4fb9-8377-43b698686445"),
                            Number = 9,
                            Title = "The Dark Warrior",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/CBwLjsNUjVxM"
                        },
                        new
                        {
                            Id = new Guid("30ae2e53-6ace-4f22-a4bc-1724cfa57ec7"),
                            AnimeId = new Guid("6503eae0-a8c8-4a30-9b71-9d1f689aa5ce"),
                            Number = 1,
                            Title = "The Strongest Man",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/cUMvPNAPKyWu"
                        },
                        new
                        {
                            Id = new Guid("42f1bdda-2032-44bb-ba7f-1b9e93daa996"),
                            AnimeId = new Guid("c08bdbf7-cd84-4351-be0d-f738c4e6955b"),
                            Number = 1,
                            Title = "Self-Proclaimed Psychic Reigen Arataka: And Mob",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/bWIC8dlQixTs"
                        },
                        new
                        {
                            Id = new Guid("416a5b51-e36d-4c49-a74e-1c1fb1b7e4dc"),
                            AnimeId = new Guid("4b3d577b-f39f-4d25-80a8-fc9015ca273e"),
                            Number = 4,
                            Title = "The Prestigious School's Interview",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/ZK7GX6YoAjhy"
                        },
                        new
                        {
                            Id = new Guid("3c66f509-4808-4842-b0bd-1e1525b3e576"),
                            AnimeId = new Guid("0891b02f-6ed9-43b9-9f73-2848be072b20"),
                            Number = 1,
                            Title = "The Self-Proclaimed Goddess and Reincarnation in Another World!",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/a3seTc4fpCKx"
                        },
                        new
                        {
                            Id = new Guid("ffb9c0e6-a0e3-44df-9a41-1e2a60b67b50"),
                            AnimeId = new Guid("6503eae0-a8c8-4a30-9b71-9d1f689aa5ce"),
                            Number = 11,
                            Title = "The Dominator of the Universe",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/qSgtNZSAvqSN"
                        },
                        new
                        {
                            Id = new Guid("13994651-c4e3-4df0-b9be-22a11c8459ae"),
                            AnimeId = new Guid("6503eae0-a8c8-4a30-9b71-9d1f689aa5ce"),
                            Number = 6,
                            Title = "The Terrifying City",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/m4dOAkVTjaST"
                        },
                        new
                        {
                            Id = new Guid("28cb4451-4035-4e7b-8514-22dd43156a7b"),
                            AnimeId = new Guid("6503eae0-a8c8-4a30-9b71-9d1f689aa5ce"),
                            Number = 9,
                            Title = "Unyielding Justice",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/E2YWSUjxdehK"
                        },
                        new
                        {
                            Id = new Guid("33ebeebf-b22c-4ad3-8393-2b58d469a26c"),
                            AnimeId = new Guid("0891b02f-6ed9-43b9-9f73-2848be072b20"),
                            Number = 9,
                            Title = "God's Blessing on This Wonderful Shop!",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/bDSsVvwvF1lb"
                        },
                        new
                        {
                            Id = new Guid("dd3465ad-0f09-48f8-b026-2d05eb481bf7"),
                            AnimeId = new Guid("4b3d577b-f39f-4d25-80a8-fc9015ca273e"),
                            Number = 8,
                            Title = "The Counter-Secret Police Cover Operation",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/BQgUFsmlH6qI"
                        },
                        new
                        {
                            Id = new Guid("68749189-fa2a-4bf3-afae-2fd5fe3b732b"),
                            AnimeId = new Guid("0891b02f-6ed9-43b9-9f73-2848be072b20"),
                            Number = 5,
                            Title = "A Price for This Cursed Sword!",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/1SnPE2DneFfJ"
                        },
                        new
                        {
                            Id = new Guid("d1f8cb2b-3b01-4b66-aa34-30f283228fe5"),
                            AnimeId = new Guid("abab9632-5b43-4fb9-8377-43b698686445"),
                            Number = 8,
                            Title = "Twin Swords of Slashing Death",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/RBVvIoXkxOO6"
                        },
                        new
                        {
                            Id = new Guid("fb99035b-9f98-4ac4-8d10-32208ae5a0d2"),
                            AnimeId = new Guid("c08bdbf7-cd84-4351-be0d-f738c4e6955b"),
                            Number = 11,
                            Title = "Master: Leader",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/7vfTxR11Zuc9"
                        },
                        new
                        {
                            Id = new Guid("9605a205-07c1-4fdf-944a-3ac610258fd2"),
                            AnimeId = new Guid("c08bdbf7-cd84-4351-be0d-f738c4e6955b"),
                            Number = 7,
                            Title = "Exaltation: I've Obtained Loss",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/k67I3HTiCbCD"
                        },
                        new
                        {
                            Id = new Guid("27440846-c2cb-44e7-b3d2-4c9304e48335"),
                            AnimeId = new Guid("abab9632-5b43-4fb9-8377-43b698686445"),
                            Number = 3,
                            Title = "Battle at Carne Village",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/vIVR9y88VCiR"
                        },
                        new
                        {
                            Id = new Guid("4f82bcad-64f4-4c8f-9232-4d5ec50c7af8"),
                            AnimeId = new Guid("6503eae0-a8c8-4a30-9b71-9d1f689aa5ce"),
                            Number = 4,
                            Title = "The Modern Ninja",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/E39nLWDhxN4c"
                        },
                        new
                        {
                            Id = new Guid("8020b824-19c9-4614-bf65-52c6a7295b1e"),
                            AnimeId = new Guid("abab9632-5b43-4fb9-8377-43b698686445"),
                            Number = 12,
                            Title = "The Bloody Valkyrie",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/mZihm4ohYKZx"
                        },
                        new
                        {
                            Id = new Guid("93013965-f4e1-40f4-8af1-52cb7fc654a0"),
                            AnimeId = new Guid("4b3d577b-f39f-4d25-80a8-fc9015ca273e"),
                            Number = 1,
                            Title = "Operation〈Strix〉",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/Cx2LxhSjvzIl"
                        },
                        new
                        {
                            Id = new Guid("be647c99-fcd1-4485-9768-54299e17d82a"),
                            AnimeId = new Guid("dac27489-f999-48ec-a8de-661d192b08eb"),
                            Number = 1,
                            Title = "Full",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/TdDzKPpzhXLV"
                        },
                        new
                        {
                            Id = new Guid("575a7183-ef82-4d12-901c-59c319c5f2a2"),
                            AnimeId = new Guid("4b3d577b-f39f-4d25-80a8-fc9015ca273e"),
                            Number = 6,
                            Title = "The Friendship Scheme",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/opRXdgfY7WYZ"
                        },
                        new
                        {
                            Id = new Guid("dfbfb49f-cfa2-41d4-b761-5b4063be1529"),
                            AnimeId = new Guid("4b3d577b-f39f-4d25-80a8-fc9015ca273e"),
                            Number = 3,
                            Title = "Prepare for the Interview",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/Aj1qF2XU6mcW"
                        },
                        new
                        {
                            Id = new Guid("75b038d2-7b2a-4dd7-b6f2-5fb10c176d9e"),
                            AnimeId = new Guid("9c571d74-b29c-4541-b396-e5d0770b9a46"),
                            Number = 1,
                            Title = "Full",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/jE9bfWi1qXON"
                        },
                        new
                        {
                            Id = new Guid("286d2695-4841-4c2b-a11f-6c6a281f771f"),
                            AnimeId = new Guid("0891b02f-6ed9-43b9-9f73-2848be072b20"),
                            Number = 4,
                            Title = "Explosion Magic for This Formidable Enemy!",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/mRMoDddXkslG"
                        },
                        new
                        {
                            Id = new Guid("e5ae251e-ed37-46c8-a77b-75bd6868b538"),
                            AnimeId = new Guid("abab9632-5b43-4fb9-8377-43b698686445"),
                            Number = 11,
                            Title = "Confusion and Understanding",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/VMQrtpfgWCIc"
                        },
                        new
                        {
                            Id = new Guid("403d0f80-3466-4d66-ac54-76af1706472a"),
                            AnimeId = new Guid("abab9632-5b43-4fb9-8377-43b698686445"),
                            Number = 1,
                            Title = "End and Begging",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/xdOEopgCoCcU"
                        },
                        new
                        {
                            Id = new Guid("a7151915-aeac-435f-80af-796a27ce01d0"),
                            AnimeId = new Guid("f50a5dbd-8fcf-4977-90d9-fd416b1ffff5"),
                            Number = 1,
                            Title = "Full",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/bpKOub3l6Gm1"
                        },
                        new
                        {
                            Id = new Guid("3b27a9e4-d3b7-4f12-aa84-7fa478cae2f6"),
                            AnimeId = new Guid("6503eae0-a8c8-4a30-9b71-9d1f689aa5ce"),
                            Number = 10,
                            Title = "Unparalleled Peril",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/VEk1CxisgBAk"
                        },
                        new
                        {
                            Id = new Guid("57ceaba5-9478-4dc8-be16-822eb2178808"),
                            AnimeId = new Guid("4b3d577b-f39f-4d25-80a8-fc9015ca273e"),
                            Number = 10,
                            Title = "The Great Dodgeball Plan",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/OVFpoAF0UD9O"
                        },
                        new
                        {
                            Id = new Guid("398ef1aa-b97d-42b3-aba3-825ec775e605"),
                            AnimeId = new Guid("6503eae0-a8c8-4a30-9b71-9d1f689aa5ce"),
                            Number = 7,
                            Title = "The Ultimate Disciple",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/dwXXQaNdQERR"
                        },
                        new
                        {
                            Id = new Guid("06666464-bba4-40b1-af25-84c962d7f05a"),
                            AnimeId = new Guid("c08bdbf7-cd84-4351-be0d-f738c4e6955b"),
                            Number = 9,
                            Title = "\"Claw\": 7th Division",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/DHNd1gyPo8sq"
                        },
                        new
                        {
                            Id = new Guid("618bc35d-5dda-450e-b918-84fe748f6d45"),
                            AnimeId = new Guid("0891b02f-6ed9-43b9-9f73-2848be072b20"),
                            Number = 7,
                            Title = "A Second Death in This Freezing Season!",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/yddK4WkNwozl"
                        },
                        new
                        {
                            Id = new Guid("429d3c6a-e661-45b7-bc3f-89886e62e57c"),
                            AnimeId = new Guid("4b3d577b-f39f-4d25-80a8-fc9015ca273e"),
                            Number = 9,
                            Title = "Show Off How in Love You Are",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/yLi5ZDECJvvP"
                        },
                        new
                        {
                            Id = new Guid("db9ce3e0-8f72-4298-98fe-90c0860b653f"),
                            AnimeId = new Guid("c08bdbf7-cd84-4351-be0d-f738c4e6955b"),
                            Number = 6,
                            Title = "Discord: To Become One",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/fpQ12LYUDlr5"
                        },
                        new
                        {
                            Id = new Guid("da333d65-d81d-4146-a7ee-9c53a61b85de"),
                            AnimeId = new Guid("6503eae0-a8c8-4a30-9b71-9d1f689aa5ce"),
                            Number = 2,
                            Title = "The Lone Cyborg",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/xpsSYz8hVnbH"
                        },
                        new
                        {
                            Id = new Guid("b6454f33-ce23-420f-9100-a4306027cbfb"),
                            AnimeId = new Guid("abab9632-5b43-4fb9-8377-43b698686445"),
                            Number = 13,
                            Title = "Player VS Non Player Character",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/XvOTzmIfmqmW"
                        },
                        new
                        {
                            Id = new Guid("a34bf3d1-04f8-40bf-8fe8-a6d83258f034"),
                            AnimeId = new Guid("4b3d577b-f39f-4d25-80a8-fc9015ca273e"),
                            Number = 5,
                            Title = "Will They Pass or Fail",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/qRmlFup6t81H"
                        },
                        new
                        {
                            Id = new Guid("846636da-9f99-4996-848e-ad70f862fa66"),
                            AnimeId = new Guid("4b3d577b-f39f-4d25-80a8-fc9015ca273e"),
                            Number = 2,
                            Title = "Secure a Wife",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/Us7g0JAeiZHa"
                        },
                        new
                        {
                            Id = new Guid("78082805-b3ea-4992-bc90-b37ec7c58e6b"),
                            AnimeId = new Guid("c08bdbf7-cd84-4351-be0d-f738c4e6955b"),
                            Number = 4,
                            Title = "Idiots Only Event: Kin",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/J6lzLG1T2C4L"
                        },
                        new
                        {
                            Id = new Guid("1032c177-0d48-43a7-ab66-b949cea78bf2"),
                            AnimeId = new Guid("abab9632-5b43-4fb9-8377-43b698686445"),
                            Number = 7,
                            Title = "Wise King of Forest",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/TZfmSzIGXojU"
                        },
                        new
                        {
                            Id = new Guid("c24f422f-295e-4e6e-b0d4-bc75fcdd1b4a"),
                            AnimeId = new Guid("abab9632-5b43-4fb9-8377-43b698686445"),
                            Number = 5,
                            Title = "Two Adventurers",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/Yr4L8CNpZ8sg"
                        },
                        new
                        {
                            Id = new Guid("72a25996-5caa-4377-aa0d-c71fa728db72"),
                            AnimeId = new Guid("abab9632-5b43-4fb9-8377-43b698686445"),
                            Number = 4,
                            Title = "Ruler of Death",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/6p36OszqNlVY"
                        },
                        new
                        {
                            Id = new Guid("af9ac3f1-23ea-4d16-9d6a-cdce86d5934b"),
                            AnimeId = new Guid("c08bdbf7-cd84-4351-be0d-f738c4e6955b"),
                            Number = 2,
                            Title = "Doubts About Youth: The Telepathy Club Appears",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/FTID8eN7bmaf"
                        },
                        new
                        {
                            Id = new Guid("10cdcae2-c578-4cdd-a6fc-ce4382b74f1f"),
                            AnimeId = new Guid("0891b02f-6ed9-43b9-9f73-2848be072b20"),
                            Number = 10,
                            Title = "Final Flame for This Over-the-Top Fortress!",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/hcugTYnowxbM"
                        },
                        new
                        {
                            Id = new Guid("173d44d4-4b0b-4562-b8b4-d03be69d2276"),
                            AnimeId = new Guid("abab9632-5b43-4fb9-8377-43b698686445"),
                            Number = 6,
                            Title = "Journey",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/SoHCsvdCrE4Y"
                        },
                        new
                        {
                            Id = new Guid("a43c2816-e471-4754-bec0-d87742ddfcc4"),
                            AnimeId = new Guid("6503eae0-a8c8-4a30-9b71-9d1f689aa5ce"),
                            Number = 5,
                            Title = "The Ultimate Mentor",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/Ll3bzNuIuy87"
                        },
                        new
                        {
                            Id = new Guid("5ec138a9-73af-416c-8d60-d9a926248b71"),
                            AnimeId = new Guid("0891b02f-6ed9-43b9-9f73-2848be072b20"),
                            Number = 6,
                            Title = "A Conclusion to This Worthless Fight!",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/uhlbzQBxVNTP"
                        },
                        new
                        {
                            Id = new Guid("f337c35e-5736-4364-ba33-dd5d19aa358f"),
                            AnimeId = new Guid("abab9632-5b43-4fb9-8377-43b698686445"),
                            Number = 10,
                            Title = "True Vampire",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/xLOTRSQX3LSr"
                        },
                        new
                        {
                            Id = new Guid("c65a5457-b7e2-48f7-be7f-de6b1ce8a044"),
                            AnimeId = new Guid("6503eae0-a8c8-4a30-9b71-9d1f689aa5ce"),
                            Number = 3,
                            Title = "The Obsessive Scientist",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/gqLR3t46hUiu"
                        },
                        new
                        {
                            Id = new Guid("afd7eaaa-e818-4003-99fa-e85ec34ada97"),
                            AnimeId = new Guid("0891b02f-6ed9-43b9-9f73-2848be072b20"),
                            Number = 3,
                            Title = "A Panty Treasure in This Right Hand!",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/lZlteKlBUBSx"
                        },
                        new
                        {
                            Id = new Guid("c4600512-ce9a-4d52-8b51-ec5a95741b10"),
                            AnimeId = new Guid("0891b02f-6ed9-43b9-9f73-2848be072b20"),
                            Number = 2,
                            Title = "An Explosion for This Chunibyo!",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/FNyOwCh68gIl"
                        },
                        new
                        {
                            Id = new Guid("fc10a19e-7fe7-48be-b0c5-f1d0d62bdcf7"),
                            AnimeId = new Guid("c08bdbf7-cd84-4351-be0d-f738c4e6955b"),
                            Number = 3,
                            Title = "An Invite to a Meeting: Simply Put, I Just Want to Be Popular",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/s8tiCNwNc6YD"
                        },
                        new
                        {
                            Id = new Guid("b0fd5dd6-7f79-437c-b59f-f1f949a8d375"),
                            AnimeId = new Guid("0891b02f-6ed9-43b9-9f73-2848be072b20"),
                            Number = 8,
                            Title = "A Loving Hand for Out Party When We Can't Make It Through Winter!",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/NAR8odfd096D"
                        },
                        new
                        {
                            Id = new Guid("730b50af-c3dc-4a42-a05c-f40625f45d14"),
                            AnimeId = new Guid("4b3d577b-f39f-4d25-80a8-fc9015ca273e"),
                            Number = 7,
                            Title = "The Target's Second Son",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/JoQtIAC6IKft"
                        },
                        new
                        {
                            Id = new Guid("adfc1b37-f553-4f8d-b764-f453d406aab1"),
                            AnimeId = new Guid("c08bdbf7-cd84-4351-be0d-f738c4e6955b"),
                            Number = 12,
                            Title = "Mob and Reigen: A Giant Tsuchinoko Appears",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/ipXtooFVN5G8"
                        },
                        new
                        {
                            Id = new Guid("8556adba-fcf7-4d84-96f8-f45d2a09ed4b"),
                            AnimeId = new Guid("6503eae0-a8c8-4a30-9b71-9d1f689aa5ce"),
                            Number = 8,
                            Title = "The Deep Sea King",
                            VideoUrl = "https://rapid-cloud.ru/embed-6/NwuICrNNKF7L"
                        });
                });

            modelBuilder.Entity("Animu.Data.Entities.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8706d54-6814-4a77-9edd-04fc36dce612"),
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = new Guid("c8880554-0cde-4c8a-9fe9-e65d227f4976"),
                            Name = "Action"
                        });
                });

            modelBuilder.Entity("Animu.Data.Entities.TagAnime", b =>
                {
                    b.Property<Guid>("TagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnimeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TagId", "AnimeId");

                    b.HasIndex("AnimeId");

                    b.ToTable("TagAnimes");

                    b.HasData(
                        new
                        {
                            TagId = new Guid("c8706d54-6814-4a77-9edd-04fc36dce612"),
                            AnimeId = new Guid("0891b02f-6ed9-43b9-9f73-2848be072b20")
                        },
                        new
                        {
                            TagId = new Guid("c8706d54-6814-4a77-9edd-04fc36dce612"),
                            AnimeId = new Guid("abab9632-5b43-4fb9-8377-43b698686445")
                        },
                        new
                        {
                            TagId = new Guid("c8880554-0cde-4c8a-9fe9-e65d227f4976"),
                            AnimeId = new Guid("abab9632-5b43-4fb9-8377-43b698686445")
                        },
                        new
                        {
                            TagId = new Guid("c8880554-0cde-4c8a-9fe9-e65d227f4976"),
                            AnimeId = new Guid("dac27489-f999-48ec-a8de-661d192b08eb")
                        },
                        new
                        {
                            TagId = new Guid("c8706d54-6814-4a77-9edd-04fc36dce612"),
                            AnimeId = new Guid("6503eae0-a8c8-4a30-9b71-9d1f689aa5ce")
                        },
                        new
                        {
                            TagId = new Guid("c8880554-0cde-4c8a-9fe9-e65d227f4976"),
                            AnimeId = new Guid("6503eae0-a8c8-4a30-9b71-9d1f689aa5ce")
                        },
                        new
                        {
                            TagId = new Guid("c8880554-0cde-4c8a-9fe9-e65d227f4976"),
                            AnimeId = new Guid("9c571d74-b29c-4541-b396-e5d0770b9a46")
                        },
                        new
                        {
                            TagId = new Guid("c8706d54-6814-4a77-9edd-04fc36dce612"),
                            AnimeId = new Guid("c08bdbf7-cd84-4351-be0d-f738c4e6955b")
                        },
                        new
                        {
                            TagId = new Guid("c8880554-0cde-4c8a-9fe9-e65d227f4976"),
                            AnimeId = new Guid("c08bdbf7-cd84-4351-be0d-f738c4e6955b")
                        },
                        new
                        {
                            TagId = new Guid("c8706d54-6814-4a77-9edd-04fc36dce612"),
                            AnimeId = new Guid("4b3d577b-f39f-4d25-80a8-fc9015ca273e")
                        },
                        new
                        {
                            TagId = new Guid("c8880554-0cde-4c8a-9fe9-e65d227f4976"),
                            AnimeId = new Guid("f50a5dbd-8fcf-4977-90d9-fd416b1ffff5")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "0207d09a-18ed-4216-b1f8-1a09d7d9a8c2",
                            ConcurrencyStamp = "77af0181-ea5d-4358-92ab-c768cb900b85",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "07090e31-f8aa-483b-beab-d6283397f417",
                            ConcurrencyStamp = "d30205b4-57a2-4878-8902-1a09327ccc9a",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "02e1a366-d7fe-40de-97d1-75609b134609",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3aa6bc49-bb3e-4c79-882a-adf3a4fb6f12",
                            Email = "user@abv.bg",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "USER@ABV.BG",
                            NormalizedUserName = "USER@ABV.BG",
                            PasswordHash = "AQAAAAEAACcQAAAAECZFsYqsEL3pyQMswJFXTHyyAz38cg4HquY5t+3UsmlFOcL8s4qlaEpBcWdwzBmggw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "WCJAHPAJPP25QOL6QKTSBLBQVJLWDKXG",
                            TwoFactorEnabled = false,
                            UserName = "user@abv.bg"
                        },
                        new
                        {
                            Id = "852e04c1-3bed-47e3-83f1-91bd27665215",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "978785aa-63dd-40be-a891-8fbe66e4da17",
                            Email = "admin@abv.bg",
                            EmailConfirmed = false,
                            LockoutEnabled = true,
                            NormalizedEmail = "ADMIN@ABV.BG",
                            NormalizedUserName = "ADMIN@ABV.BG",
                            PasswordHash = "AQAAAAEAACcQAAAAEC4yWooIOwEVd+yOsNYSBiDXGIV16ZqeeTqOBRUe8KdxdqoNi2/Ev8uu78ubZcsfJw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4OETGRAEQCBGW2N3J5EM36QY4XIZPWGV",
                            TwoFactorEnabled = false,
                            UserName = "admin@abv.bg"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "02e1a366-d7fe-40de-97d1-75609b134609",
                            RoleId = "0207d09a-18ed-4216-b1f8-1a09d7d9a8c2"
                        },
                        new
                        {
                            UserId = "852e04c1-3bed-47e3-83f1-91bd27665215",
                            RoleId = "07090e31-f8aa-483b-beab-d6283397f417"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Animu.Data.Entities.Episode", b =>
                {
                    b.HasOne("Animu.Data.Entities.Anime", "Anime")
                        .WithMany("Episodes")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");
                });

            modelBuilder.Entity("Animu.Data.Entities.TagAnime", b =>
                {
                    b.HasOne("Animu.Data.Entities.Anime", "Anime")
                        .WithMany("TagAnimes")
                        .HasForeignKey("AnimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Animu.Data.Entities.Tag", "Tag")
                        .WithMany("TagAnimes")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anime");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Animu.Data.Entities.Anime", b =>
                {
                    b.Navigation("Episodes");

                    b.Navigation("TagAnimes");
                });

            modelBuilder.Entity("Animu.Data.Entities.Tag", b =>
                {
                    b.Navigation("TagAnimes");
                });
#pragma warning restore 612, 618
        }
    }
}
